name: Auto Collect and Process

on:
  # 每 6 小时自动运行一次
  schedule:
    - cron: '0 */6 * * *'
  # 支持手动点击运行
  workflow_dispatch:

jobs:
  run-aggregator:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Aggregator
        env:
          GIST_PAT: ${{ secrets.GIST_PAT }}
          GIST_LINK: ${{ secrets.GIST_LINK }}
        # 使用 python 运行 process.py，并指定你的配置文件
        run: python subscribe/process.py -s subscribe/config/my-config.json -n 32 -t 5000

